name: Update GitHub Stats

on:
  schedule:
    - cron: '0 */12 * * *'  # Runs every 12 hours
  workflow_dispatch:        # Allow manual run

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate GitHub Stats
        run: |
          curl -H "Authorization: token ${{ secrets.GH_STATS_TOKEN }}" \
            "https://github-readme-stats.vercel.app/api?username=yzes95&show_icons=true&theme=radical" \
            -o stats.png

          curl -H "Authorization: token ${{ secrets.GH_STATS_TOKEN }}" \
            "https://github-readme-stats.vercel.app/api/top-langs/?username=yzes95&layout=compact&theme=radical" \
            -o langs.png

      - name: Commit files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update stats images"
