name: Update GitHub Stats

on:
  schedule:
    - cron: "0 */12 * * *"   # Runs every 12 hours
  workflow_dispatch:          # Allow manual trigger

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generate GitHub Stats Images
        run: |
          curl -L -H "Authorization: token ${{ secrets.GH_STATS_TOKEN }}" \
            "https://github-readme-stats-git-masterrstaa-rickstaa.vercel.app/api?username=yzes95&show_icons=true&theme=radical" \
            -o stats.png

          curl -L -H "Authorization: token ${{ secrets.GH_STATS_TOKEN }}" \
            "https://github-readme-stats-git-masterrstaa-rickstaa.vercel.app/api/top-langs/?username=yzes95&layout=compact&theme=radical" \
            -o langs.png

      - name: Commit stats images
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update GitHub stats images"
          file_pattern: "stats.png langs.png"
